---
name: Check go.mod dependencies
on:
  workflow_call:
    inputs:
      tag:
        type: string
        required: true
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
        with:
          ref: refs/heads/${{github.event.workflow_run.head_branch}}

      - name: Check go.mod deps
        run: |
          cat go.mod |
          grep 'github.com/ljkiraly/.* v' |
          grep -v 'github.com/networkservicemesh/govpp.*' |
          grep -v 'github.com/networkservicemesh/vpphelper.*' |
          grep -v 'github.com/ljkiraly/.* ${{ inputs.tag }}' || exit 0;
          exit 1;
