---
name: Pull Request on update/* Branch Push
on:
  workflow_call:
    secrets:
      token:
        required: true
jobs:
  auto-pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Construct PR message
        run: |
          PULL_REQUEST_BODY=$(git log --format="%s%nCommit: %h%nAuthor: %an%nDate: %ad" -n 1)
          echo "$PULL_REQUEST_BODY"
          echo "PULL_REQUEST_BODY<<EOF" >> $GITHUB_ENV
          echo "$PULL_REQUEST_BODY" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      - name: pull-request-action
        uses: vsoch/pull-request-action@1.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.token }}
          BRANCH_PREFIX: "update/"
          PULL_REQUEST_BRANCH: "main"
